#Hugo configuration
title = "wqeasdwqe"
baseURL = "https:\/\/adfsdf.zxcv.ads"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
